### ISSUE TITLE
For the competency dashboard, add the translated competency wording (see attached files)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#100]
(High Priority)

From what I understand, you will be discussing with Stephane the integration of this dashboard.

[Tag translations.docx](https://github.com/pila-project/pila-platform/files/15185278/Tag.translations.docx)

**Comment by jasonford** [comment]
@OECDPILA Second link seems to be broken

**Comment by jasonford** [comment]
We can help with this. We're awaiting the full set competency tag translations from this issue too: https://github.com/pila-project/pila-platform/issues/97

**Comment by OECDPILA** [comment]
I should get these around thursday this week

**Comment by OECDPILA** [comment]
Here is the updated file for remaining translations: 

[Final translations for Games.docx](https://github.com/pila-project/pila-platform/files/15274009/Final.translations.for.Games.docx)

**Comment by OECDPILA** [comment]
Here is the correct doc: 
[Tag translations for the platform.docx](https://github.com/pila-project/pila-platform/files/15289623/Tag.translations.for.the.platform.docx)

**Comment by OECDPILA** [comment]
Flagging that the student dashboard and 'retry' button are also not translated...
![image](https://github.com/pila-project/pila-platform/assets/145113767/92aa019a-8c85-4bdb-9cae-b6e8ca5729bb)
