### ISSUE TITLE
Feedback from Thai colleague on PILA create app - FUNCTIONALITIES to implement BY WORKSHOP

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#103]
(High Priority) 

By order of priority:

- [x] - In rearranging item type - 1) allow for both horizontal and vertical lines of images; 2) add numbers and see if we get further feedback.
- [x] - The text-to-speech voice is weird - can we slow down the pace and make the voice sound more natural? Matt to check if there are other settings, but if not - we can leave for now. complete
- [x] - ~~Add a down arrow in the drop-down menu after selecting + to create new (see screenshot)~~ complete

![image](https://github.com/pila-project/pila-platform/assets/145113767/0856dd8f-4b7a-4c7e-a84d-83e7e1df5ce8)

After discussion on 03 May, we decided:
- NOT to implement this change because it prevents other types of items from being implemented -In matching item, make sure that ONLY ONE line can be connected from one dot to another dot. 
- Leave additional development for the rearranging item type to later - after we get more feedback from teachers.

**Comment by OECDPILA** [comment]
Example mock-up for the rearranging item (spoke with Eren and I think we can wait on implementing the second column solution for now - since this introduces additional functionality questions/potential bugs): 
![image](https://github.com/pila-project/pila-platform/assets/145113767/b3a32257-5055-4ba7-9250-a990cbf35290). I think creating a border around within which the numbers sit can help reduce questions about the images themselves being "attached" to those numbers. Also, implementing a grey square with question mark behind can help clarify that students need to decide the right image for first place, second place, etc. Happy to discuss further or for you guys to go in a diff direction.

**Comment by mthomasmcclain** [comment]
On the voice, I did the minimal improvements we can do presently.  I slowed down the voice a bit (90%) and on some browsers in _english only_ it will play a nicer auto-voice.  But the auto-voices are all pretty mediocre, and there's no consistent cross-browser guarantees.  If we don't like auto play the auto play, we can always turn them off for an item or items.

**Comment by mthomasmcclain** [comment]
check out the updated player for the reordering question.  that pattern, too, will be helpful with future types where we want learners to drag "cards" or images or whatnot into defined space.
