### ISSUE TITLE
UI/UX for the 'Create' page in the Teacher account

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#107]
(Medium priority)

Jason, you mentioned in a comment that you welcomed any UI/UX suggestions for the new 'create' page. Sruthi has mocked this up, which I think is quite nice. The 'P' icon is a placeholder for the last preview image that Sonia will provide. 

![image](https://github.com/pila-project/pila-platform/assets/145113767/9a5713c9-2be8-4455-a442-25986307da94)

**Comment by OECDPILA** [comment]
![Untitled_Artwork (1)](https://github.com/pila-project/pila-platform/assets/145113767/56f39fff-8373-4557-954e-a0f958199f8c)
 (instead of the P for Pila Create)

**Comment by jasonford** [comment]
Thanks @mthomasmcclain !
