### ISSUE TITLE
Could you create a mixed sequence with "normal" Candli and two Karel tasks?

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#108]
(Low priority)

In the sequence:
-Candli level tutorial
-Candli level 1
-6b25807e-6a7b-4295-94fa-76692b36a42f 
-2a1d37c5-5233-4f87-beda-c2c92c40cf3a

This will help us show how Cand.li can be used for multiple types of experiences, as well as how we have the ability to mix multiple types of content into one sequence...

**Comment by jasonford** [comment]
Created and tagged as PILA Thailand PILA Content! I can change the title and add any preview image as you prefer.

87d1fe60-0998-11ef-9899-83d810e01611ta

**Comment by OECDPILA** [comment]
Thanks a lot @jasonford ! If you can please remove the 'Return to map!'  at the end of each of the Candli levels, that would be great. But not urgent as it still works. From what I gather, the old 'candli' dashboard no longer works? (I tried on the PILA International platform).

**Comment by jasonford** [comment]
corrected UUID: 87d1fe60-0998-11ef-9899-83d810e01611
