### ISSUE TITLE
Competency Dashboard for Candli games is showing the correct number of students in the class, but not the correct students or data for those students

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#111]
(High Priority)

When I click on the other 'EDU PILA', I see the same data across all four "students".
![image](https://github.com/pila-project/pila-platform/assets/145113767/4e52e433-0811-467c-9c1a-8815a8604009)

**Comment by jasonford** [comment]
Fixed with: https://github.com/pila-project/pila-platform/commit/c7ac71f132cddb7add222577c4b351471a29c8fc
