### ISSUE TITLE
Sequence wrapper not recognizing or updating attempts and completion for Candli games 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#112]
![image](https://github.com/pila-project/pila-platform/assets/145113767/6adb454a-9f86-493a-ac73-b395fd6e7d63)
(I had finished the first two games)

**Comment by vs-ranjani** [comment]
Wanted to add that this is the same across games, not just Candli.
![image](https://github.com/pila-project/pila-platform/assets/168413098/e8cfcaae-e6cc-4292-98e6-1047cf37a492)

**Comment by jasonford** [comment]
Candli and Karel now reporting completion on successful completion of tasks
