### ISSUE TITLE
Browser compatibility for laptops (Apple, Windows, Linux...)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#115]
(High priority)

Please send list of browser compatibility for PILA so that our organizers can contact the participants.

Candli's is:
chrome: '>=92
firefox: '>=75’
safari: '>=14.5'
edge: '>=92'
samsung_internet: '>=16'

**Comment by jasonford** [comment]
From testing, it looks like we're good to go for:

safari >= 15.6
firefox >= 94
chrome >= 98
edge >= 98
samsung_internet >= 18
