### ISSUE TITLE
Errors on PILA live monitoring dashboard 

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#116]
When a student completes all activities in a sequence, it does not get reflected properly on the PILA live monitoring dashboard (the task counter does not show 3/3). Completed tasks are also not shown in green. 
![candlidashboardpila](https://github.com/pila-project/pila-platform/assets/168413098/f3e86c9b-c0b9-4748-ac6e-efcc7874e6ed)

**Comment by jasonford** [comment]
Includes Karel content

**Comment by vs-ranjani** [comment]
I just double-checked this again with Karel, and as Matt said, it doesn't count attempts, only solved tasks that are done using the right number of blocks. Sorry for the false alarm!
![image](https://github.com/pila-project/pila-platform/assets/168413098/76eaf222-5c64-4820-8578-88a12153a0ba)

**Comment by mthomasmcclain** [comment]
I think Karel items are okay.  To fix this I believe we need / want Candli items to surface the close / correct when successfully completed.

**Comment by jasonford** [comment]
I'll leave this open until I fix the candli correct reporting

**Comment by jasonford** [comment]
Candli is reporting correct on completion of experiences!
