### ISSUE TITLE
Lag Observed When Pressing 'A' Key - Investigation Needed Across Macbook and Desktop/Laptop Platforms

### ISSUE THREAD

**Issue by Danielalopez0797** [pila-project/pila-platform#119]
https://github.com/pila-project/pila-platform/assets/168447956/69f72c67-9edb-4231-af58-34bd3cf7123a

**Comment by jasonford** [comment]
@Danielalopez0797 could you help us isolate the issue by seeing if you see the same behavior in these spots?:

PILA Thailand teacher account preview
https://cand.li/dev/testing-release-pila/pila-play.html?game=c8c710aa7fee5af189791f64fc8270d6
https://embed.knowlearning.systems/7d7c4c3b-e7a1-4588-bb78-a859fffccfac

**Comment by jasonford** [comment]
@stephanemagnenat I notices this "lag" as well, but maybe it's just a "hit-box" issue for chirpy? Going to close here as well, but again, happy to re-open if this helps you track PILA issues as well!

**Comment by stephanemagnenat** [comment]
I never saw the lag outside PILA, and didn't test enough within PILA to say anything about the PILA context. I do not think it is a Candli/hitbox issue though.
