### ISSUE TITLE
PILA Creator App - Implement translation and font changes for tool itself (waiting for feedback from Thai colleagues)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#120]
(Medium Priority)

-Implement translation changes for the tool itself (will send these once our colleague shares feedback)
-Change Thai font to a more modern style (using an open source style) : TBD - the partners will share a font with us next week.

**Comment by stephanemagnenat** [comment]
Fyi, in Candli, we are using [Noto for the Thai font](https://fonts.google.com/noto/specimen/Noto+Sans+Thai), as it is metric-compatible with Roboto.

**Comment by OECDPILA** [comment]
@jasonford  @mthomasmcclain - here are the font proposals from our Thai colleagues: 

1.https://www.f0nt.com/release/sanamdeklen-chaya/
2.https://fonts.google.com/noto/specimen/Noto+Sans+Thai+Looped?query=Thai
3.https://fonts.google.com/noto/specimen/Noto+Serif+Thai?noto.query=Thai&noto.lang=th_Thai&noto.region=TH&noto.script=Thai

Here are the text changes they have requested in the tool:
[translations proposal.docx](https://github.com/pila-project/pila-platform/files/15237163/translations.proposal.docx)

**Comment by stephanemagnenat** [comment]
As mentioned above, be aware to select a compatible font otherwise mixed text will look weird (that is the motivation behind the creation of Noto, which is a wide-support font metric compatible with Roboto).
