### ISSUE TITLE
Integrate simplified Betty's Brain units into PILA

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#122]
(High Priority)

Links to get from Grayson (because I believe he needs to add something specific to make them appear as the "primary-level" versions...

Also, we are sending for translation tomorrow, so I am not sure how that impacts WHEN these can/should be integrated.

**Comment by OECDPILA** [comment]
@jasonford this requires syncing with Grayson. I think he has to do something specific to the links...

**Comment by jasonford** [comment]
Will do! is it just the Photosynthesis and Predator-Prey modules you want to add?

**Comment by OECDPILA** [comment]
Yes, just the Photosynthesis and Predator-Prey modules in the simplified version! Thanks

**Comment by jasonford** [comment]
Integrated! This did expose an issue with how the dashboard was filtering student data, but I have notified Grayson about where the fix needs to be. The Photosynthesis dashboard works, but the Predator-Prey one needs an update on the BB side to work.

**Comment by OECDPILA** [comment]
Thanks @jasonford !
