### ISSUE TITLE
Please change the image for the 'Learning to Program Karel' sequence to the Karel preview image (rather than the generic PILA one)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#123]
(Medium priority)

**Comment by jasonford** [comment]
@OECDPILA, you can adjust this with a hidden menu in the customizer. Just open the content in create.pilaproject.org and shift + click the top left of the tan box of sequence items. That will show an interface where you can select the Karel image or even upload any you want.

**Comment by OECDPILA** [comment]
Closed - thanks!
