### ISSUE TITLE
Please change the name of the "See Dashboard (Candli)" to "Competency Dashboard" and "See Dashboard" to "Live-Monitoring Dashboard" (see screenshot)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#124]
(High Priority)

![image](https://github.com/pila-project/pila-platform/assets/145113767/b5579b1f-579e-4ae5-8b6a-7e1d15e6195a)

**Comment by mthomasmcclain** [comment]
Done.  Will need thai re-translation (along with any/all other wording changes).
