### ISSUE TITLE
Live monitoring dashboard not reliably showing results

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#129]
(High priority)

In the ~~Karel~~ Candli tasks, the dashboards were not showing the correct completion information (they had all finished all three tasks) : 
![image](https://github.com/pila-project/pila-platform/assets/145113767/d6364a9c-6535-44d8-928e-127bcd28b08f)

**Comment by jasonford** [comment]
@OECDPILA the screenshot looks like its for Candli experiences, and if that's the bug then I think this https://github.com/pila-project/pila-platform/issues/133 might be the root issue and should be easy to fix. Were you seeing this on other dashboards for Karel content?

**Comment by OECDPILA** [comment]
As far as I know, the dashboard for Karel content was working well.

**Comment by jasonford** [comment]
Fixed with: https://github.com/knowlearning/matching/pull/54
