### ISSUE TITLE
For Karel sequences, the native 'student' feedback did not populate correctly for one student (see screenshot)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#130]
(High Priority)

On a Windows computer in Chrome, this student could only see this of their "student" dashboard:
![image](https://github.com/pila-project/pila-platform/assets/145113767/1aca6c06-00eb-409a-bb1c-a710aa0baab8)

**Comment by jasonford** [comment]
@OECDPILA was this behavior seen even after a reload? Thanks for including the console! It looks like there was a network error on this request and I'm wondering if that is repeatable?

**Comment by OECDPILA** [comment]
Yes, it was still seen after reload. He can reproduce it today (see screenshot), and it appears that everything shows up but just in white text so when he highlights it with his mouse, he can see it (see second screenshot).
![9F168CA2](https://github.com/pila-project/pila-platform/assets/145113767/77128b5b-5f54-4142-ac53-1e318752b7a8)
![CBFFB03B](https://github.com/pila-project/pila-platform/assets/145113767/e57df265-b463-4f81-a6e1-15f6e1354127)

Thanks!

**Comment by jasonford** [comment]
@OECDPILA thanks for the context! This appears to be totally a styling thing. Very unexpected... but I think there should be an easy fix. I implemented it with https://github.com/knowlearning/matching/commit/022779d25fc4090b2e93519eb0fe894f0edc7fa1 and will close this if you can confirm it worked.

**Comment by OECDPILA** [comment]
Happy for you to close @jasonford - the person this happened to is out until Monday so we won't be able to confirm.

**Comment by jasonford** [comment]
Sure thing! The fix is safe but pretty heavy handed, so barring some really strange issue, this should be fixed.
