### ISSUE TITLE
In the translation tool for Karel, the sequences we want to add do not appear for translation

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#137]
HIGH PRIORITY

- 2e305e40-0355-11ef-93e9-2d92a5e8a142
- 4aa5a5f0-0358-11ef-b689-97b7f3c71ff8
- 7ef7e220-0356-11ef-81e1-8d359ad54350
- 9ece77e0-0346-11ef-a9e6-dfaacaa2a0a4
- d352cd50-0354-11ef-93e9-2d92a5e8a142
- 43784bd0-0357-11ef-81e1-8d359ad54350
- 2d3e07a0-0358-11ef-b689-97b7f3c71ff8
- 51a424b0-0355-11ef-93e9-2d92a5e8a142
- bcd01900-0356-11ef-81e1-8d359ad54350
- 9fbcf8c0-0355-11ef-93e9-2d92a5e8a142

**Comment by mthomasmcclain** [comment]
I spot tested a few of those sequence items, and I _think_ all of the enclosed Karel items are there to translate.

On the "Sequence Builder", if you "shift-click" any of the items in the sequence it will show you the id of that item.  If you do that, and the translate-karel site is missing any of the Karel items, please reopen with the Karel item that's missing!

**Comment by OECDPILA** [comment]
Thanks @mthomasmcclain - I have sent all of the task IDs!
