### ISSUE TITLE
Minor UI changes for Teacher account with Thai language

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#139]
(Medium priority)

- [x] Increase the width of the menu so that the title of the second page is not cut-off (see screenshot)
- [x] Translate 'new assignment' (example title) in the assignment tab 
![image](https://github.com/pila-project/pila-platform/assets/145113767/74f99ae7-5ce3-4ce0-8968-030b77f53ce4)
![image](https://github.com/pila-project/pila-platform/assets/145113767/5ab26030-02a5-417a-8e53-7496db565e9d)

**Comment by mthomasmcclain** [comment]
Added that translation.

For the thai name overrunning the sidebar, can you give the device, browser, and window size?  It looks ok for me everywhere I've tested it.

<img width="889" alt="Screenshot 2024-05-08 at 8 34 07 PM" src="https://github.com/pila-project/pila-platform/assets/36894807/6595629b-4dff-48b9-9633-a1f8564a9b4f">

**Comment by OECDPILA** [comment]
I have tested too and it looks good wherever I see it. Happy to close this.
