### ISSUE TITLE
Teacher Competency Dashboard - it appears there is a bug with how the scores are appearing for 'comparison' in Ocean Cleanup game

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#142]
(High priority)

There is an issue in how the information is reporting on comparison for the ocean cleanup (level 1). Could it be adding up multiple tries?
![image](https://github.com/pila-project/pila-platform/assets/145113767/64f3e535-b786-4997-ba99-4ffbdfcd67d4)

**Comment by jasonford** [comment]
@stephanemagnenat This looks to be from the reporting on the candli side? Just want to confirm in case there is something I can do in the competency dashboard to fix.

**Comment by stephanemagnenat** [comment]
@jasonford absolutely, I asked Sonia to investigate. I assume that it is a variable that is not maxed out or something like that.

**Comment by stephanemagnenat** [comment]
I found the bug, it is that for better score, the comparison variable is incremented by +2 and +3 instead of +1 each.

**Comment by stephanemagnenat** [comment]
I fixed it in the English version of the game.

**Comment by stephanemagnenat** [comment]
And now the Thai version.

**Comment by stephanemagnenat** [comment]
@OECDPILA it should be completed now, can you please try and close the bug? Of course, existing score will never go back, but it should be ok for new students.

**Comment by OECDPILA** [comment]
I just created a new assignment and assigned the 'math underwater...' activity. I then opened the teacher dashboard to monitor. My second 'Emma Linsenmayer' account has the correct information, but I can also see the old results for my other Emma Linsenmayer account (I know this because we see the 6/3 and I only attempted the first two tasks). This leads me to think that student data is not being "cleared" for each new assignment. Hope this helps debug! Thanks
New results:
![image](https://github.com/pila-project/pila-platform/assets/145113767/b4d460cb-7784-47ea-b126-a0ec88e3d28a)

Old results:
![image](https://github.com/pila-project/pila-platform/assets/145113767/7963559c-48b4-4431-b231-363e7885be18)

**Comment by jasonford** [comment]
@stephanemagnenat Thanks for the updates! I'll be able to close out all the bugs on my end now.

@OECDPILA I have the competency states being global now for testing purposes, but I will scope them to the assignments today (this will fix that issue you see where new assignments see old data)
