### ISSUE TITLE
Create app - Order items type bug with randomization

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#143]
(Medium priority) 
I was testing the rearrange item type using Butterfly task. The randomized ordering had it so I started with the correct answer (which would be quite confusing for students). We spoke to Eren about this and he said he fixed it, so there may still be something wrong with the solution?
@erenkahraman @mthomasmcclain

**Comment by erenkahraman** [comment]
Refactored the shuffleImages function to ensure that the shuffled order doesn't match the correct order. I made a while loop to repeatedly shuffle the images until a different order is generated from the correct order. It's fixed on my localhost now.

**Comment by mthomasmcclain** [comment]
@erenkahraman I took a look at the branch, and it's great with an important tweak/guard needed.  That "sort" method will infinite loop and crash if someone tries to preview a question with zero or one items. (That would be a silly problem, but we don't want that eventuality to break that app!).  If you just add a guard for array length, we'll merge and close.

**Comment by mthomasmcclain** [comment]
@erenkahraman Thanks for the update.  Merged that branch (on the other project) and closing.

**Comment by erenkahraman** [comment]
@mthomasmcclain  Thanks a lot for the feedback Matt! I totally agree and it was a crucial detail that I overlooked when I first set up the function. It must be fixed now.
