### ISSUE TITLE
Integrate Thai versions of all Cand.li tasks in the same way as we did for the two sequences.

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#146]
(High Priority)

Will update this issue with links today or tomorrow (depending on translation), but wanted to flag that this still needs to be done. Each game has a separate URL for the Thai version.

**Comment by OECDPILA** [comment]
Here are the Thai versions of the games!

Math invaders: https://cand.li/dev/testing-release/play?5f4092d3956e53c98ccec3da0a2f3925
Chirpy Easy: https://cand.li/dev/testing-release/play?f4cb3e4fe72355f58e6b58d458d31205
Chirpy Medium: https://cand.li/dev/testing-release/play?e8d0ab2438765c1c9dd9962d10444a0c
Chirpy Hard: https://cand.li/dev/testing-release/play?4a95faed0b105822adc1d90c96c4b645
Ocean Cleanup Easy: https://cand.li/dev/testing-release/play?6f48841b58af5d8aa450ae5f9258f1ec
Ocean Cleanup Hard: https://cand.li/dev/testing-release/play?237d32dc23cc59e680ed47ec2e3a4fb5
Magical Mixology: https://cand.li/dev/testing-release/play?de6a2f6f709e57a1b3aa6358a5a8d0bb
Gravity: https://cand.li/dev/testing-release/play?93690465d42f52058c92404e329651be
Mushroom Mayhem: https://cand.li/dev/testing-release/play?a1c31030facc58d688a07040e25771db
Conservation of Momentum: https://cand.li/dev/testing-release/play?ba07adc0589f5f3a990f995cc54b8efd

**Comment by jasonford** [comment]
URLs need a little update:

https://cand.li/dev/testing-release-pila/pila-play.html?game=5f4092d3956e53c98ccec3da0a2f3925

Can use embed tool to manage images and such:

https://embed.knowlearning.systems/

**Comment by jasonford** [comment]
Individual Cand.li task images cropped from the originals:

![math-invaders](https://github.com/pila-project/pila-platform/assets/1317275/cf545d76-6f26-46c3-aedc-526db0630cba)
![paper](https://github.com/pila-project/pila-platform/assets/1317275/1b52d632-6530-4582-8268-b09c749ef69d)
![gravity](https://github.com/pila-project/pila-platform/assets/1317275/4be86b4c-1231-45de-afb8-59e132016872)
![mushroom-mayhem](https://github.com/pila-project/pila-platform/assets/1317275/4f86c684-6a67-48c0-8ebb-4592eb6ee458)
![magical-mixology](https://github.com/pila-project/pila-platform/assets/1317275/a77d76f9-ef58-43c9-84b9-1243a691d478)
![save-the-oceans](https://github.com/pila-project/pila-platform/assets/1317275/420a652e-de21-4dd2-9cf5-5585c8ed6d42)
![chirpy](https://github.com/pila-project/pila-platform/assets/1317275/58f31b96-d883-4b4b-8c21-068fb55d9770)

**Comment by OECDPILA** [comment]
These are integrated and tagged. I just am waiting for the translated science titles to finalise and close the issue. Thanks!

**Comment by OECDPILA** [comment]
All should be correct now! Thanks
