### ISSUE TITLE
Bug: "New Assignment" button is not working

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#147]
(High priority)

I tried on both my Windows and Apple computer and the assignment button is not working.
Here is a screenshot of the Console:
![image](https://github.com/pila-project/pila-platform/assets/145113767/ebd69da6-45a7-4e35-8471-318df9d2f5f2)

**Comment by mthomasmcclain** [comment]
yep, i broke that with a typo in my fix of the translation item.  fixing now.

**Comment by mthomasmcclain** [comment]
fixed
