### ISSUE TITLE
Karel translations do not reflect in PILA create when I build a sequence of Karel tasks

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#150]
My browser settings are set to Thai as default. When I drag and drop Karel tasks into the sequence wrapper from the Karel customiser, they render in English. 

![image](https://github.com/pila-project/pila-platform/assets/168413098/02844d2d-f993-4aa0-ae6b-23a9a9001886) - PILA sequence wrapper
![image](https://github.com/pila-project/pila-platform/assets/168413098/c4c76d05-e80e-4e76-a876-90ad91ab4170) - karel customiser

**Comment by mthomasmcclain** [comment]
fixed
