### ISSUE TITLE
Competency dashboard not showing translated names for Thai sequences

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#153]
(High Priority)

In this assignment, I assigned the new 'Be a scientist!' Thai version. It doesn't seem to be recognising that it should show the competency dashboard. I am using Firefox (and checked it in Chrome) and I also tried refreshing, but it still didn't appear.

![image](https://github.com/pila-project/pila-platform/assets/145113767/a218bdfb-e94f-424a-9d72-9b4793606b6b)

Here are the UUIDs for the new activities in Thai:
- 87f37b90-0ee7-11ef-bbd8-13a3d43c1666 (math underwater..)
- f93c2f40-0ee7-11ef-bbd8-13a3d43c1666 (leveling up with math)
- b56c1100-0ee6-11ef-bbd8-13a3d43c1666 (be a scientist)

UPDATE: assignments to those sequences now show the dashboard, but we still need to:

- [ ] Add translated sequence names to dashboard

**Comment by jasonford** [comment]
Thanks for the uuids @OECDPILA !

I made it so it will appear for assignments for those sequences too.

There is some work left to do (I'll add it to the description for this issue) to translate the names on the competency dashboard.

**Comment by jasonford** [comment]
@stephanemagnenat on looking to insert the game names in the dashboard, I see that you are serving them via your api endpoint (https://cand.li/api/v0/gameNames/GAME_ID). Cool! I'm happy to  hack a shortcut into the competency dashboard repo for the translated Thai sequence names, but if you want to/have time to modify them on your end, here are the translated mappings:

Be a Scientist! -> "เป็นนักวิทยาศาสตร์!"
Leveling Up With Math -> "ยกระดับด้วยคณิตศาสตร์"
Math Underwater... -> "คณิตศาสตร์ใต้น้ำ, บนบก & ในอากาศ"

Just let me know if you prefer I do the hack on the dashboard end!

**Comment by stephanemagnenat** [comment]
Game names are indeed translated on the Candli side, as they have a nice representation there as you have seen.

I am confused about your question related to the sequences though, as I do not understand how I could ever modify them "on my end", as these have no existence on "my end". Also, the competency dashboard is not aware of the sequence it is showing as far as I know. Or am I missing something?

**Comment by jasonford** [comment]
@stephanemagnenat Ah, of course, I pulled the sequence names, but I should have pulled the game titles!  Here's the actually possibly helpful map for you:

"4a95faed0b105822adc1d90c96c4b645" -> "การผจญภัยของเชิร์พปี้ (ระดับยาก)"
"237d32dc23cc59e680ed47ec2e3a4fb5" -> "อนุรักษ์ท้องทะเล (ระดับกลาง)"
"de6a2f6f709e57a1b3aa6358a5a8d0bb" -> "ศาสตร์แห่งการปรุงน้ำเวทมหัศจรรย์"

"a1c31030facc58d688a07040e25771db" -> "เห็ดจอมซน"
"93690465d42f52058c92404e329651be" -> "แรงโน้มถ่วง"
"ba07adc0589f5f3a990f995cc54b8efd" -> "การอนุรักษ์โมเมนตัม"

"f4cb3e4fe72355f58e6b58d458d31205" -> "การผจญภัยของเชิร์พปี้ (ระดับง่าย)"
"6f48841b58af5d8aa450ae5f9258f1ec" -> "อนุรักษ์ท้องทะเล (ระดับง่าย)"
"5f4092d3956e53c98ccec3da0a2f3925" -> "คณิตพิชิตเอเลี่ยน"
"e8d0ab2438765c1c9dd9962d10444a0c" -> "การผจญภัยของเชิร์พปี้ (ระดับกลาง)"

**Comment by stephanemagnenat** [comment]
@jasonford do you mean that game titles have not been translated? If so that is an oversight from our side! I will transmit these to Sonia!

**Comment by jasonford** [comment]
@stephanemagnenat thanks for ending them along! Yep, the new sequence names are coming through as "Chirpy's Adventure Hard THAI" etc.

**Comment by stephanemagnenat** [comment]
@soniahorne is now working on that!

**Comment by soniahorne** [comment]
It's updated and should now be translated correctly into Thai!

**Comment by jasonford** [comment]
Thank you @soniahorne !
