### ISSUE TITLE
Image size on preview images - can you please replace the images for the sequences that you have created that are PILA content?

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#162]
(Medium priority - will help with load time!)

Here are the smaller sizes of images for the sequences that you are "owner" of in the creator app?
-Betty's Brain tasks
-English version of the candli sequences
-Clean our oceans
-Karel and Candli 

I have done the thai sequences of candli and Karel tasks.

![Save_the_ocean](https://github.com/pila-project/pila-platform/assets/145113767/fe9e2291-df2e-4e04-a670-a32d886ae5e2)
![Karel_Card_Preview](https://github.com/pila-project/pila-platform/assets/145113767/999d1328-c691-44f2-9771-fba8706b0b55)
![Pila_Logo](https://github.com/pila-project/pila-platform/assets/145113767/94dc9937-b311-4532-8d42-9488d2fde008)
![Betty's_Brain_Card_Preview (2)](https://github.com/pila-project/pila-platform/assets/145113767/9c913098-f9e5-46a4-a9fb-575447827acc)
![Sequence #3 Name_ Leveling up with math](https://github.com/pila-project/pila-platform/assets/145113767/1aa43184-815d-4d43-b080-8a6028a6a1ef)
![Sequence #1 Name_ Be a Scientist! (1)](https://github.com/pila-project/pila-platform/assets/145113767/3465494e-8f51-4154-9c19-d42932a4aa3c)
![Sequence #2 Name_ Math underwater, on land   in the air! (1)](https://github.com/pila-project/pila-platform/assets/145113767/92c06006-0b99-4999-9488-485ff38c5b42)

**Comment by jasonford** [comment]
Done!
