### ISSUE TITLE
For several people, they could not see the student dashboard after playing through the game because the font was white.

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#163]
(High priority)

I also took a screenshot of the Console, but then tried the highlighting trick and you could indeed see the information.

![bug in student dashboard](https://github.com/pila-project/pila-platform/assets/145113767/30c2e01a-92e8-46f1-bfb8-82457b08fbd5)

**Comment by mthomasmcclain** [comment]
@OECDPILA To clarify, when this happened you could highlight text (with the cursor) under the three stars? (for example if you wanted to copy and paste it out).  I think that's what you meant, but want to be sure because if so that narrows down issue quite a bit.

**Comment by mthomasmcclain** [comment]
Implemented a fix that I'm 95% sure will work, but I can't reproduce to test!  Please reopen if you see this again.
