### ISSUE TITLE
Bug? - Teacher getting kicked out of their account and then SSO asking to re-login (multiple times)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#164]
I took a picture of the console when it happened, but not sure if helpful for investigations. It only seemed to be a problem for one or two people.

![Kickedoutofaccount](https://github.com/pila-project/pila-platform/assets/145113767/a1d8ebb7-6ebf-4fc3-be5e-0ed74cf4e69f)

**Comment by jasonford** [comment]
@OECDPILA did this happen repetitively or did it eventually resolve itself and the user was able to log in in that browser? If it was happening repetitively and they could not log in, it could be an issue with session ids getting set and permissions at the browser level. In any case, it would be helpful to track down this kind of bug if you could enable "Preserve log" in the dev tools so we can see logs from all the pages that pop up in the authentication process:

[Screencast from 2024-05-17 12-22-29.webm](https://github.com/pila-project/pila-platform/assets/1317275/b0925390-b3bc-43d8-9d00-6a6039137593)

**Comment by jasonford** [comment]
@OECDPILA I opened https://github.com/knowlearning/platform/issues/26 to track this internally

**Comment by OECDPILA** [comment]
@jasonford  I am not sure if this is the same issue, but one of the participants who created an account last week and used it yesterday can no longer login because it goes to the SSO screen, he tries to sign in with his google email and then it just immediately goes back to the SSO screen (rather than to his account). I cleared the browser history, tried on multiple browsers and on different wifis, but nothing seemed to fix it.

**Comment by OECDPILA** [comment]
![screenshot3](https://github.com/pila-project/pila-platform/assets/145113767/badeb7b0-30c7-4692-865a-79099075f018)
![screenshot2](https://github.com/pila-project/pila-platform/assets/145113767/27fc6786-c5d0-4fd0-b0f2-20875fd8935f)
![Screenshot](https://github.com/pila-project/pila-platform/assets/145113767/810523ed-3585-47e9-a23c-0fa557327e00)

Here are some images for more context!
