### ISSUE TITLE
Can you please make Mario and our colleague at EEF an admin of PILA Thailand so they can approve teachers?

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#165]
(High priority)

Mario - let me know if you need his UUID

**Comment by jasonford** [comment]
Sure thing @OECDPILA !

We can add both easily, but we will need Mario's uuid. Mind sending it over email?

**Comment by mthomasmcclain** [comment]
Golf now has admin access.  Awaiting Mario's user id.

**Comment by jasonford** [comment]
@OECDPILA will close for now, but feel free to email over Mario's UUID if you want us to add it!
