### ISSUE TITLE
For Candli sequences, would it be possible to adjust the feedback given in the three bubbles at the top?

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#166]
In the sequence wrapper, there is a lot of confusion about why they see 'red' circles when in fact they got 3 stars (as a student) according to the Candli scoring rules. This is because we loosened the threshold for achieving three stars (80% if my memory serves me). Many of the participants never moved on because they kept trying to solve to see the green checkmark. Would it be possible to either:
a) simplify to show just a filled in circle that would communicate which task they are on;
b) adjust thresholds to match those of the competency dashboards, which would require adding a yellow circle for 1-2 stars and providing green for whatever three stars is; OR
c) remove these three dots, which would also allow them to focus more on the little left/right arrows below for changing tasks?
Depending on what makes sense, we may want to remove the 'correct: 0/1" on the upper right-hand corner too.

Another piece of feedback was that the dash in the dots were confusing, because people thought they were minus signs. 
![image](https://github.com/pila-project/pila-platform/assets/145113767/936e3e2f-27a7-4f79-b849-68a98ba3b370)

**Comment by mthomasmcclain** [comment]
We changed the sequence wrapper so those little circles never go red for Candli items. (You either get green if 3 stars, or stay indeterminate as you keep trying.). I think that's the good fix for now, and we can discuss otherer adjustments in of big "lessons learned" and "next steps" conversations!

Also, we see the competency dashboard is still using 0.85 as the cutoff for 3-stars. We kept the sequence player in alignment.  We can change both together if you would give the go ahead.
