### ISSUE TITLE
The foundation EEF has requested that we include a small icon of a chatbot for troubleshooting requests

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#169]
(Medium priority)

Can we include a floating icon that shows up in the bottom left-hand corner of the side menu that allows for trainers/teachers to contact someone at the foundation for help? If someone clicks on it, they would need to see a small window that could put for general help: email XXXXX and for emergencies: call XXXXX at XXXXX. I will get exact wording + translation from my colleague tomorrow.

we could use this from Fonzy (our illustrator), but make it quite small?
![Chatbot Fonzy](https://github.com/pila-project/pila-platform/assets/145113767/aefce70d-c278-4490-8b6d-f0dca2d69751)

**Comment by mthomasmcclain** [comment]
What's your phone number Emma? 😛

**Comment by OECDPILA** [comment]
Thankfully they will be directed to our Thai colleagues :) I just need to figure out which work phone and email they want to use

**Comment by mthomasmcclain** [comment]
We just implemented a change where the text just says (in English or Thai as appropriate) "For support please email your trainer."  If you would like that text updated, let us know.
