### ISSUE TITLE
On iOS in Safari, the icons are not showing up correctly for the PILA Teacher account and in the PILA Create tool (for adding audio, images, menu options, etc.)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#171]
(High Priority)

Here is a screenshot of the PILA create tool (but they also cannot see the icons in the side menu of the PILA teacher account).
<img width="1440" alt="Screenshot 2567-05-23 at 13 23 25" src="https://github.com/pila-project/pila-platform/assets/145113767/d9bd865e-afb3-478f-a47a-2d26b5c0ef66">

**Comment by jasonford** [comment]
@OECDPILA is this also the case on Chrome for the users? I'm investigating on my end and can hopefully fix soon, but there's a chance Chrome will work on iOS if you need a stop-gap

**Comment by jasonford** [comment]
@OECDPILA I think I might have fixed the issue for iOS Safari. Can you confirm?

**Comment by OECDPILA** [comment]
It worked!

**Comment by OECDPILA** [comment]
It seems that the icons are not working on all macbooks in Safari

**Comment by jasonford** [comment]
@OECDPILA is that for create and the main app?

**Comment by OECDPILA** [comment]
For both!

**Comment by mthomasmcclain** [comment]
I just pushed a change that has a high probability of fixing this. I can't be 100% sure because I can't reproduce the bug on any of my macs with safari, so it's based on _similar_ problems with font-awesome i found on the web.  **Please reopen if you see again or get further reports.**

**Comment by mthomasmcclain** [comment]
I just pushed a change that has a high probability of fixing this. I can't be 100% sure because I can't reproduce the bug on any of my macs with safari, so it's based on _similar_ problems with font-awesome i found on the web. **Please reopen if you see again or get further reports.**
