### ISSUE TITLE
URGENT - for the PILA Creator app, when we add 'new' types of questions they go directly to the play version (rather than the customiser)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#174]
(High priority)

When we try to add new items of ANY type, it opens up the playable student-facing versions of the example items, rather than the customiser screen. 

![image](https://github.com/pila-project/pila-platform/assets/145113767/2061f0da-3f0a-478e-8adc-fb8e64998ed0)

**Comment by mthomasmcclain** [comment]
I believe this is/was the result of a very slow or disconnected service.  It is working for me presently.  Can anyone confirm that it's working on the other end?

Nonetheless, it should behave better if disconnected or slow. (( Certainly not just somehow show an example view. )) I'll take a look at that.

**Comment by mthomasmcclain** [comment]
Pushed a fix for most imaginable cases. Fingers crossed.
