### ISSUE TITLE
In the PILA Creator App, the editing of text boxes was not available in the matching question on Safari on Macbook

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#175]
(Low priority)

It worked when the participant switched to Chrome.

**Comment by mthomasmcclain** [comment]
<img width="573" alt="Screenshot 2024-05-28 at 7 52 07 AM" src="https://github.com/pila-project/pila-platform/assets/36894807/7495a2c2-2b62-4503-9d78-52c6e4ce6b35">

**Comment by mthomasmcclain** [comment]
I tried to fix for quite a while, and apparently this is a deep browser bug with foreignObjects in SVG that Chromium has fixed but not Safari.

https://issues.chromium.org/issues/41388813

Our options are to 1. wait for Safari to fix, which could be a while and ignore in the meantime, or 2. redesign the editor so the safari bug is circumvented.

**Comment by mthomasmcclain** [comment]
Implemented a hacky middle-ground fix.  On "edit" text shrinks so moveable.  Doesn't look amazing, but successfully tested on Safari and Chrome. Not student facing, only on customizer / builder.

<img width="609" alt="Screenshot 2024-06-03 at 10 03 30 AM" src="https://github.com/pila-project/pila-platform/assets/36894807/76c9190a-c34d-4315-9eca-36cfbdd05782">
