### ISSUE TITLE
Student dashboard showing up in English when playing a Thai map of Candli tasks 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#183]
![image](https://github.com/user-attachments/assets/4f3d5ff8-c785-4268-bda9-da09039f65db)

Is there anyway to ensure the dashboard appears in Thai when the content of the activity is in Thai?

**Comment by mthomasmcclain** [comment]
If the browser "prefers" English, this is the expected behaviour.  It will be in English to the greatest degree possible, and fallback to Thai only if no English found.  If we are getting these English strings even when the browser prefers Thai, please reopen.
