### ISSUE TITLE
On PILA International, adding new content modal has message 'incorrect URL or ID' constantly

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#186]
![image](https://github.com/user-attachments/assets/bdfc4dec-22b2-487f-932f-7f35ba702946)
When I click on 'Add content by URL or ID', the message already exists that there is an incorrect URL or ID. When I pasted a UUID, the message remained. 
It is also awkward that the button says 'Cancel' in green. When I clicked on Cancel, it added the content. 

I then tried to import it through the 'Create' tab and it says 'Success!' but then does not show up in the library.

**Comment by mthomasmcclain** [comment]
This was two bugs, both closed.  The first (the layout / invalid message) was superceded as you requested removing the card that shows add content. (Still can add from the other teacher tab.)  The second bug was content not adding correctly on Intl, and is now fixed.
