### ISSUE TITLE
Add customiser tools (Karel, betty, new authoring tools) to PILA Thailand teacher accounts

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#55]
in the 'Explore and Create' page

**Comment by jasonford** [comment]
I split "explore and create" into separate tabs for "explore" and "create." I think this might be a nicer/cleaner layout, but happy to do other options. Also happy to style the page with recommendations.

Closed with: https://github.com/pila-project/pila-platform/commit/31054add95505f92a3a0d67baf2002de2625196a
