### ISSUE TITLE
Change the side bar to take up less space (see screenshot) AND replace icon on side bar for 'Explore and Create' to new icon (see link in description) 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#56]
We think it would be better to make the side menu always present but to shorten it - relying mostly on the icons to illustrate (like on Teams - see image here). We don't want to change the wording, but rather make the words smaller and have them in the narrow menu bar. This will be particularly useful for the library view when there will be the tagging menu!
![image](https://github.com/pila-project/pila-platform/assets/145113767/56a6698d-de04-4a41-8070-9cb8d48fefee)

New icon for 'Explore and Create':
https://fontawesome.com/icons/magnifying-glass-plus?f=classic&s=solid

**Comment by mthomasmcclain** [comment]
Done
