### ISSUE TITLE
Fix bug on previewing the assignment modal when you click 'new assignment', which currently displays too big.

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#57]
I am using Windows 10. It happens in Chrome and Firefox.

![New Assignment](https://github.com/pila-project/pila-platform/assets/145113767/2c2ef25b-a37b-40b7-a065-ec3564ef491f)

**Comment by jasonford** [comment]
Fixed with https://github.com/pila-project/pila-platform/commit/ecf03376fcbe8706d0b0fff8ab0f9b57805e9a97 !
