### ISSUE TITLE
Please move the 'settings' button from top right-hand side of screen to the bottom of the sidebar menu (see image)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#58]
(low priority) 

![image](https://github.com/pila-project/pila-platform/assets/145113767/0e10296c-a927-4d12-9d0d-176379040a9d)

**Comment by jasonford** [comment]
Closed with https://github.com/pila-project/pila-platform/commit/e3c302aba4f5ebd8b5a240d02ae4f2ff15898f81
