### ISSUE TITLE
Across most pages in the teacher account when you open a modal, the top part is cut off by the main PILA bar (see images)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#59]
(medium priority)

I am using Windows 10 and on Chrome.

![image](https://github.com/pila-project/pila-platform/assets/145113767/5e18012e-0cfc-48b0-908d-8b00529de4ea)
![image](https://github.com/pila-project/pila-platform/assets/145113767/25675cd3-dd2d-4c42-ad98-a7b572e15a8a)
![image](https://github.com/pila-project/pila-platform/assets/145113767/31c68dfe-7a63-4e50-93fc-0ecc3dffee41)

**Comment by jasonford** [comment]
https://github.com/pila-project/pila-platform/commit/ecf03376fcbe8706d0b0fff8ab0f9b57805e9a97 !
