### ISSUE TITLE
In explore and create page of teacher account, when I click 'add content by ID or URL', an error message appears without trying to input anything

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#60]
(low priority)

Can you trigger this alert only if 'some content' has been entered?

![image](https://github.com/pila-project/pila-platform/assets/145113767/b040ea27-b223-4e5e-9189-e63a01cdacbe)

**Comment by jasonford** [comment]
We removed that modal, so I'll close this one. (We're tracking the functionality in the new page on this issue: https://github.com/pila-project/pila-platform/issues/84)
