### ISSUE TITLE
Thai PILA teacher role request doesn't turn up on EDUPILA admin account

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#71]
I was able to get access to a teacher account on my personal email (veenavinjamuri12@gmail.com) without having to be approved by an admin. My role request doesn't appear in the admin account. 

![image (5)](https://github.com/pila-project/pila-platform/assets/168413098/9a1ce560-283b-472d-a74f-7dabe0935400)
![image](https://github.com/pila-project/pila-platform/assets/168413098/3295b74a-e9ec-4a09-a4c5-8a1bd93ee3d0)

**Comment by OECDPILA** [comment]
I want to add to this issue that Eren tried to create a teacher account, and I could not see his name in the role requests either. I then added his ID by using the button 'Add Teachers'. I could then see another person, but it said 'Daniela Lopez'. I refreshed and it then said 'Eren Kahraman'. When Eren tried to see his teacher account after I had "granted" him access, he still needed access...
If useful, his ID is : 86ede41d-9397-4ac6-b025-67aaaa888022
![image](https://github.com/pila-project/pila-platform/assets/145113767/432fd6b1-e271-4780-b6e1-ce77312dc585)

**Comment by jasonford** [comment]
The adding behavior from the first comment is fixed with https://github.com/pila-project/pila-platform/commit/f4a6a82269d4f15b77c8e814c067d0b553658797

the second comment is a rendering bug (goes away on refresh), so I'll keep this issue open until that is done

**Comment by jasonford** [comment]
second comment fixed with: https://github.com/pila-project/pila-platform/commit/e567499e13e053cdb9194f6c8356159b30b9b4c9
