### ISSUE TITLE
In the PILA Thai admin account, when I click on the button 'Add teachers', I get a message about tagging.

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#72]
(High priority)

Shouldn't this be a link?

![image](https://github.com/pila-project/pila-platform/assets/145113767/534a004f-acff-4f77-a472-0463e5c7b4cb)

**Comment by jasonford** [comment]
Ah yeah, that popup is a bit misleading. That "Add Teacher" button is a way to add a teacher directly with their user id. We'll update that. The only link that needs to be shared to make a request for a teacher role is thailand.pilaproject.org/teacher

We'll update that popup. Thanks!

**Comment by jasonford** [comment]
Cleared up the language on that dialogue with: https://github.com/pila-project/pila-platform/commit/1fb606e6465c4245c7eb1ae85961675ad4e29682
