### ISSUE TITLE
STUDENT ACCOUNT UPDATES

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#73]
(High priority)

In the student account, would it be possible to surface the same 'PILA Thailand' blue bar at the top and then have 'My assignments' on the side menu? 

Also, can you remove studies from the student account for now?

Finally, it would be useful to add the date of the assignment on the card, as well as make the play button a 'Start' button.

![image](https://github.com/pila-project/pila-platform/assets/145113767/cec920ca-ccb8-419a-8374-712a8e23f21c)

**Comment by jasonford** [comment]
Blue bar added and studies removed with https://github.com/pila-project/pila-platform/pull/87

TODO: add assignment date (and update cards)

**Comment by jasonford** [comment]
Assignment date and cards updated as well
