### ISSUE TITLE
Remove preview from the assignment modal when you have selected a piece of content

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#74]
(Medium priority)

![image](https://github.com/pila-project/pila-platform/assets/145113767/4d4e0c94-0da2-468a-9951-c238d777c2a7)

**Comment by jasonford** [comment]
Implemented with https://github.com/pila-project/pila-platform/commit/700ba96c1d840d2c8780fcca5001fd71ac838e1c
