### ISSUE TITLE
Reload Loop with Pila Create and Main Page on IPAD

### ISSUE THREAD

**Issue by Danielalopez0797** [pila-project/pila-platform#78]
(High Priority)

https://github.com/pila-project/pila-platform/assets/168447956/5fd286c6-a90e-437b-9408-9aa859bf7946

Trials on both browsers, google chrome and Safari
Model iPad Air 2
Version iPadOS15.4

**Comment by vs-ranjani** [comment]
Wanted to add that this also happens on Safari browsers in general (regardless of device).

**Comment by jasonford** [comment]
Thanks for the report! I released a fix for this particular issue, but there are a couple more ipad specific issues I'm working on now. Please open issues for any that you see and I'll address them there
