### ISSUE TITLE
Update the UI/UX for filtering in the item library of the teacher account and UI for previewing tags of a specific activity according to PPT sent by Emma on 29 April

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#80]
(High Priority)

- [x] Improve tag selection UI
- [x] Translate tag selection UI
- [x] Improve selected metadata panel tag UI

**Comment by OECDPILA** [comment]
A small note to say that when I click on a task card - it only shows me the pila competencies tags. I have also tagged difficulty level and Swiss thai curriculum indicators, which might be useful to show here (but not in the main filtering menu for now).

**Comment by OECDPILA** [comment]
I am adding this consideration - when I click on an activity that is near the bottom of the 'Explore' page to get information on the tags and metadata for that activity, I cannot see the information (tags and metadata) because it is at the top. Can this be fixed? Here is a screenshot:
![image](https://github.com/pila-project/pila-platform/assets/145113767/eb6e2e4b-dbb6-4716-a2ce-2153b8197cb0)

**Comment by OECDPILA** [comment]
I have added two icons for processes and content area (only really applies for science and math...for now). I am not owner of the PILA Competency Tags - can you @jasonford  please change the name to 'PILA Competencies' and add this icon : fa-solid fa-user-astronaut ? Thanks!

**Comment by jasonford** [comment]
@mthomasmcclain it looks like somehow you got to be the owner of that tag! with your 0c9c64fc-559e-40d4-916b-852f6d108a17 account (Just made a post-it to show the owner image + name instead of their id on the tag domain owner field...).
