### ISSUE TITLE
Bug that is now fixed, but wanted to signal in case - loading PILA Thailand account

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#83]
(low priority)

When Mario was trying to access his teacher account on PILA Thailand earlier today, nothing was showing up correctly (acceptance of terms of use and then also his actual account. Here is the screenshot with the Console:
![Bug on PILA](https://github.com/pila-project/pila-platform/assets/145113767/f2aa72ba-9ada-4f2b-a609-b97934d31a6e)

**Comment by jasonford** [comment]
Interesting. Thanks. This looks like an issue with our hosting provider (netlify). I'd expect that kind of thing to be temporary though. Please re-open or add a new issue if you see it more and we'll keep tracking it!
