### ISSUE TITLE
Unable to add custom content via ID/URL

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#84]
When I try to add a Betty's Brain custom map via a content ID, a message pops up saying "Not yet implemented"

![image](https://github.com/pila-project/pila-platform/assets/168413098/b5ce8070-55d8-4bff-b706-8b84c2bb721b)

**Comment by OECDPILA** [comment]
(High Priority)

**Comment by vs-ranjani** [comment]
I want to add to this that it is the same issue across all custom content, not just Betty's Brain. I tried to add a link to a Karel custom sequence that I had created and the same message shows up. 
![image](https://github.com/pila-project/pila-platform/assets/168413098/826df859-05ad-4024-9084-48aafd9096f2)

**Comment by jasonford** [comment]
Added the functionality, but will track ui/ux updates in: https://github.com/pila-project/pila-platform/issues/107
