### ISSUE TITLE
Copy link button doesn't work when I'm trying to get students to join my classroom

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#85]
I am unable to copy the link that I can send to students to join my class. "Link copied" shows up even when it's not been copied. 

![image](https://github.com/pila-project/pila-platform/assets/168413098/8fef76e6-044e-44b2-b6b6-76354a4a3046)

**Comment by jasonford** [comment]
Hey! do you mind adding in which browser + operating system you're seeing this on? Browser version would help too. Thanks!

**Comment by jasonford** [comment]
no need for the os + browser. I updated to a better supported method. fixed with: https://github.com/pila-project/pila-platform/commit/76b61ab54f77bfa76dd09caea06bfa85763defe3
