### ISSUE TITLE
Add preview images for Candli and Karel 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#90]
(Medium priority)

I will send the one for general PILA sequences once Sonia sends!

![Betty's_Brain_Card_Preview](https://github.com/pila-project/pila-platform/assets/145113767/8a47a865-e0a8-407f-96d1-41232901ccf8)

![Karel_Card_Preview](https://github.com/pila-project/pila-platform/assets/145113767/4380e6fd-e413-41c9-af1e-8cc059f0e1fe)

**Comment by mthomasmcclain** [comment]
done.  i'll open new issue for waiting for image for general pila sequences fallback
