### ISSUE TITLE
Improve the rendering of the item library when creating a new assignment. 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#91]
(High Priority)

Please fix the button size, layout rendering (all items look squished because the tags show up really big, etc)...

![image](https://github.com/pila-project/pila-platform/assets/145113767/3c4e0634-76b0-4562-9092-51a6b6352ff7)

**Comment by jasonford** [comment]
Improved styles with: https://github.com/pila-project/pila-platform/commit/dfd28a196d823c1b456147fb2091dcd16ebc8fac
