### ISSUE TITLE
In the teacher account, can you adjust these UI/UX elements:

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#95]
(low priority)

- [ ] Use fewer colours throughout (there are lots of different blues, for example)
- [ ] Ensure buttons are all similar across
- [x] Add date and time of assignment in the assignment table
- [x] Capitalize 'Admin' in the side bar?
- [ ] Modernize the tables?

**Comment by jasonford** [comment]
Closing as we decided to de-prioritize. Would be good to a dedicated pass across all pages with a designer when we have the bandwidth!
