### ISSUE TITLE
Font changes are not reflected on all browsers/devices

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#96]
Low priority, but I thought it might be good to signal this.

The font change to Avenir is reflected on my personal computer's Chrome browser (only Chrome, not other browsers). On the OECD computer, the font changes are not reflected even on Chrome. 

Attaching a picture from my personal computer. 

![image](https://github.com/pila-project/pila-platform/assets/168413098/2eebc51b-d2e4-4dcb-8a9e-3a560bd5d4b9)

**Comment by mthomasmcclain** [comment]
We just updated to the Noto fonts requested by the Thai partners.  We can/should open new issues if there are future font irregularities after this change.
