### ISSUE TITLE
Add translations to the tags (see doc attached)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#97]
(High Priority)

[Tag translations.docx](https://github.com/pila-project/pila-platform/files/15180786/Tag.translations.docx)

**Comment by mthomasmcclain** [comment]
Done for all the given translations.  You should look and see if any of the others also need to be added.  If you look at the tags when in "thai" mode you'll see which ones are missing.  (Admittedly it's not pretty yet, but we can still see what's missing.)

**Comment by jasonford** [comment]
@OECDPILA I added the "Pending OECD Input" tag in case it helps organize some of the issues for you so you hopefully don't have to filter through the list so much!

**Comment by jasonford** [comment]
(you can filter by tag by clicking any tag in the main issue list)

**Comment by OECDPILA** [comment]
Here is the updated tag translations: 
[Final translations for Games.docx](https://github.com/pila-project/pila-platform/files/15274033/Final.translations.for.Games.docx)
(same document as in issue #100

**Comment by mthomasmcclain** [comment]
We actually still don't have the updated tag translations.  It just occurred to me that perhaps the wrong file was attached.  If so, please attach the new one.  In the meantime, I'm running with a mix of the "confirmed" translations and auto-translations that can be confirmed / superceded with professional ones.  

Please note, we only need / want this link (below) if we DON'T already have the ful thai translations.  If so, ignore the link and send those!

https://docs.google.com/spreadsheets/d/1bF1FgGXE-v4ZoXZmQ7yXclkUGqqbMDGmlngFHOQIs6Y/edit#gid=0

**Comment by OECDPILA** [comment]
Ah my apologies - I attached the one for Sonia instead. Here is the right document @mthomasmcclain : 
[Tag translations for the platform.docx](https://github.com/pila-project/pila-platform/files/15289618/Tag.translations.for.the.platform.docx)

**Comment by mthomasmcclain** [comment]
Wonderful.  All of the "active" tags are translated.  The thing is, there are a log of tag texts there that don't currently exist as "Competency Tags" that have been created to translate!  That's okay.  the ones we have for now work.  WHen you create those new tags (and tag things with them), please open another issue and we'll do them.
