### ISSUE TITLE
Need Preview Image for General Sequence Items

### ISSUE THREAD

**Issue by mthomasmcclain** [pila-project/pila-platform#98]
Currently the bad placeholder is the row of five circles.  We can update that image as soon as we have it.

**Comment by OECDPILA** [comment]
@mthomasmcclain @jasonford here is the preview image for the general sequence items!

![Untitled_Artwork (1)](https://github.com/pila-project/pila-platform/assets/145113767/64bbc817-0afe-4940-80f0-cd6597745cbe)

**Comment by OECDPILA** [comment]
@mthomasmcclain @jasonford here is the preview image for the general sequence items!

![Untitled_Artwork (1)](https://github.com/pila-project/pila-platform/assets/145113767/f26121c0-9459-48d6-8e6b-ad67b9c49955)

**Comment by mthomasmcclain** [comment]
Thanks. It's live now. Ugly circles gone!
